FROM anapsix/alpine-java:latest
MAINTAINER ibm.com
COPY zipkin-server-2.11.8-SNAPSHOT-exec.jar .
ENTRYPOINT ["java"]
CMD ["-jar", "zipkin-server-2.11.8-SNAPSHOT-exec.jar"]
VOLUME /var/lib/spring-cloud/config-repo
EXPOSE 9411